const std = @import("std");

pub const SFOHeader = packed struct(u160) {
    magic: packed struct(u32) {
        byte1: u8 = '\x00',
        byte2: u8 = 'P',
        byte3: u8 = 'S',
        byte4: u8 = 'F',
    } = .{},
    version: packed struct(u32) {
        major: u8 = 1,
        minor: u8 = 1,
        unknown: u16 = 0,
    } = .{},
    key_start: u32,
    data_start: u32,
    entry_count: u32,
};

// https://www.psdevwiki.com/psp/PARAM.SFO
pub const TableDataFormat = enum(u8) {
    UTF8_Special = 0x00, // NOT NULL terminated. Used in SFO's generated by the system and/or linked to an user (Game Saves and Trophies).
    UTF8 = 0x02, // NULL terminated. Can be used any character from the system fonts. The NULL byte is counted as part of the used bytes in len.
    U32 = 0x04,
};

pub const TableEntry = packed struct(u128) {
    key_offset: u16,
    data_alignment: u8 = 4,
    data_format: TableDataFormat,
    data_len: u32,
    data_max_len: u32,
    data_offset: u32,
};

pub const SFOStructure = struct {
    header: SFOHeader,
    table: []TableEntry,
    key_pool: []u8,
    data_pool: []u8,
};

const InternalEntry = struct {
    name: [:0]const u8,
    format: TableDataFormat,
    value: ?u32,
    data: ?[]const u8,
    maxsize: u32,
};

const DefaultTable = [_]InternalEntry{
    .{ .name = "MEMSIZE", .format = .U32, .value = 1, .data = null, .maxsize = 4 },
    .{ .name = "BOOTABLE", .format = .U32, .value = 1, .data = null, .maxsize = 4 },
    .{ .name = "CATEGORY", .format = .UTF8, .value = 0, .data = "MG", .maxsize = 4 },
    .{ .name = "DISC_ID", .format = .UTF8, .value = 0, .data = "UCJS10041", .maxsize = 12 },
    .{ .name = "DISC_VERSION", .format = .UTF8, .value = 0, .data = "1.00", .maxsize = 8 },
    .{ .name = "PARENTAL_LEVEL", .format = .U32, .value = @intFromEnum(ParentalControlLevel.Level1), .data = null, .maxsize = 4 },
    .{ .name = "PSP_SYSTEM_VER", .format = .UTF8, .value = 0, .data = "1.00", .maxsize = 8 },
    .{ .name = "REGION", .format = .U32, .value = 0x8000, .data = null, .maxsize = 4 },
};

fn readSFO(allocator: std.mem.Allocator, io: std.Io, path: []const u8) !SFOStructure {
    var file = try std.Io.Dir.cwd().openFile(io, path, .{});
    defer file.close(io);

    var buffer: [4096]u8 = undefined;
    var reader = file.reader(io, &buffer);
    const io_reader = &reader.interface;

    const header = try io_reader.takeStruct(SFOHeader, .little);
    var entries = try allocator.alloc(TableEntry, header.entry_count);
    for (0..header.entry_count) |i| {
        entries[i] = try io_reader.takeStruct(TableEntry, .little);
    }

    std.debug.assert(io_reader.seek == header.key_start);

    const key_len = header.data_start - header.key_start;
    const key_pool = try io_reader.readAlloc(allocator, key_len);
    errdefer allocator.free(key_pool);

    const data_pool = try io_reader.allocRemaining(allocator, .unlimited);
    errdefer allocator.free(data_pool);

    return SFOStructure{
        .header = header,
        .table = entries,
        .key_pool = key_pool,
        .data_pool = data_pool,
    };
}

pub fn prettyPrintSFO(allocator: std.mem.Allocator, io: std.Io, path: []const u8) !void {
    const sfo = try readSFO(allocator, io, path);
    std.debug.print("Header:\n", .{});
    std.debug.print("\tMagic: {}\n", .{sfo.header.magic});
    std.debug.print("\tVersion: {d}.{d}\n", .{ sfo.header.version.major, sfo.header.version.minor });
    std.debug.print("\tKey Start: 0x{X}\n", .{sfo.header.key_start});
    std.debug.print("\tData Start: 0x{X}\n", .{sfo.header.data_start});
    std.debug.print("\tEntries: {d}\n", .{sfo.header.entry_count});

    std.debug.print("\nEntries:\n", .{});
    for (sfo.table, 0..) |entry, index| {
        std.debug.print("Index: {d}\n", .{index});

        // Slice to Zero
        const keyslice = sfo.key_pool[entry.key_offset..];
        const keyname = std.mem.span(@as([*:0]u8, @ptrCast(keyslice.ptr)));

        std.debug.print("\tKey: {s}\n", .{keyname});
        std.debug.print("\tType: {s}\n", .{@tagName(entry.data_format)});
        std.debug.print("\tOffset: 0x{X}\n", .{entry.data_offset});
        std.debug.print("\tSize: {d}\n", .{entry.data_len});
        std.debug.print("\tMax Size: {d}\n", .{entry.data_max_len});

        switch (entry.data_format) {
            .UTF8_Special => {
                const data = sfo.data_pool[entry.data_offset .. entry.data_offset + entry.data_len];
                std.debug.print("\tValue: {X}\n", .{data}); // FIXME This should print a string
            },
            .UTF8 => {
                const data = sfo.data_pool[entry.data_offset .. entry.data_offset + entry.data_len];
                std.debug.print("\tValue: {s}\n", .{std.mem.span(@as([*:0]u8, @ptrCast(data.ptr)))});
            },
            .U32 => {
                const data = sfo.data_pool[entry.data_offset .. entry.data_offset + entry.data_len];
                std.debug.print("\tValue: 0x{X}\n", .{std.mem.bytesAsValue(u32, data).*});
            },
        }
    }
}

pub fn writeSFO(allocator: std.mem.Allocator, io: std.Io, path: []const u8, entries: []InternalEntry) !void {
    var data_segment = std.array_list.Managed(u8).init(allocator);
    var key_segment = std.array_list.Managed(u8).init(allocator);

    var table_entries = std.array_list.Managed(TableEntry).init(allocator);
    const PAD = [_]u8{0} ** 4;
    for (entries) |entry| {
        const data_len = switch (entry.format) {
            .UTF8_Special => entry.data.?.len,
            .UTF8 => entry.data.?.len + 1,
            .U32 => @sizeOf(u32),
        };

        const data_max_len = if (data_len % 4 == 0) data_len else data_len + 4 - (data_len % 4);

        const data_padding = PAD[0..(4 - data_len % 4)];

        try table_entries.append(.{
            .key_offset = @intCast(key_segment.items.len),
            .data_offset = @intCast(data_segment.items.len),
            .data_format = entry.format,
            .data_len = @intCast(data_len),
            .data_max_len = @intCast(data_max_len),
        });

        try key_segment.insertSlice(key_segment.items.len, entry.name);
        try key_segment.insertSlice(key_segment.items.len, "\x00");

        if (entry.format == .U32) {
            try data_segment.insertSlice(data_segment.items.len, std.mem.asBytes(&entry.value.?));
        } else {
            try data_segment.insertSlice(data_segment.items.len, entry.data.?);
        }

        if (entry.format == .UTF8) {
            try data_segment.insertSlice(data_segment.items.len, "\x00");
        }
        if (data_len % 4 != 0) {
            try data_segment.insertSlice(data_segment.items.len, data_padding);
        }
    }

    if (key_segment.items.len % 4 != 0) {
        try key_segment.insertSlice(key_segment.items.len, PAD[0..(4 - key_segment.items.len % 4)]);
    }

    const sfo = SFOStructure{
        .header = SFOHeader{
            .key_start = @intCast(@sizeOf(SFOHeader) + @sizeOf(TableEntry) * entries.len),
            .entry_count = @intCast(entries.len),
            .data_start = @intCast(@sizeOf(SFOHeader) + @sizeOf(TableEntry) * entries.len + key_segment.items.len),
        },
        .table = try table_entries.toOwnedSlice(),
        .key_pool = try key_segment.toOwnedSlice(),
        .data_pool = try data_segment.toOwnedSlice(),
    };

    const file = try std.Io.Dir.cwd().createFile(io, path, .{});
    defer file.close(io);

    var buffer_writer: [4096]u8 = undefined;
    var writer = file.writer(io, &buffer_writer);
    var io_writer = &writer.interface;

    try io_writer.writeStruct(sfo.header, .little);
    for (sfo.table) |entry| {
        try io_writer.writeStruct(entry, .little);
    }
    try io_writer.writeAll(sfo.key_pool);
    try io_writer.writeAll(sfo.data_pool);
    try io_writer.flush();
}

pub fn main(init: std.process.Init) !void {
    const allocator: std.mem.Allocator = init.arena.allocator();
    const commands = (try init.minimal.args.toSlice(allocator))[1..];

    const io = init.io;

    if (commands.len == 0) {
        std.debug.print("Usage: sfotool <read | write>\n", .{});
        std.process.exit(1);
    }

    const com = commands[0];
    if (std.mem.eql(u8, com, "read")) {
        if (commands.len < 2) {
            std.debug.print("Usage: sfotool read <file>\n", .{});
            std.process.exit(1);
        }
        try prettyPrintSFO(allocator, io, commands[1]);
    } else if (std.mem.eql(u8, com, "write")) {
        if (commands.len < 3) {
            std.debug.print("Usage: sfotool write <TITLE> <out.sfo>\n", .{});
            std.process.exit(1);
        }
        const entries = try allocator.alloc(InternalEntry, 1 + DefaultTable.len);
        entries[DefaultTable.len] = .{
            .name = "TITLE",
            .format = .UTF8,
            .value = null,
            .data = commands[1],
            .maxsize = @intCast(commands[1].len + if (commands[1].len % 4 != 0) 4 - (commands[1].len % 4) else 0),
        };

        for (0..DefaultTable.len) |i| {
            entries[i] = DefaultTable[i];
        }

        try writeSFO(allocator, io, commands[2], entries);
    } else {
        std.debug.print("Usage: sfotool <read | write>\n", .{});
        std.process.exit(1);
    }
}

// See https://manuals.playstation.net/document/en/psp/current/settings/parental.html
pub const ParentalControlLevel = enum(u32) {
    Level1 = 1,
    Level2 = 2,
    Level3 = 3,
    Level4 = 4,
    Level5 = 5,
    Level6 = 6,
    Level7 = 7,
    Level8 = 8,
    Level9 = 9,
    Level10 = 10,
    Level11 = 11,
};
