// POSIX errno mapping for sceNetInet BSD socket calls.
// Values sourced from pspdev/newlib sys/errno.h.

const c = @import("../../c/modules.zig");
const inet = c.sceNetInet;

pub const ErrnoError = error{
    EPERM,
    ENOENT,
    ESRCH,
    EINTR,
    EIO,
    ENXIO,
    E2BIG,
    ENOEXEC,
    EBADF,
    ECHILD,
    EAGAIN,
    ENOMEM,
    EACCES,
    EFAULT,
    ENOTBLK,
    EBUSY,
    EEXIST,
    EXDEV,
    ENODEV,
    ENOTDIR,
    EISDIR,
    EINVAL,
    ENFILE,
    EMFILE,
    ENOTTY,
    ETXTBSY,
    EFBIG,
    ENOSPC,
    ESPIPE,
    EROFS,
    EMLINK,
    EPIPE,
    EDOM,
    ERANGE,
    ENOMSG,
    EIDRM,
    ECHRNG,
    EL2NSYNC,
    EL3HLT,
    EL3RST,
    ELNRNG,
    EUNATCH,
    ENOCSI,
    EL2HLT,
    EDEADLK,
    ENOLCK,
    EBADE,
    EBADR,
    EXFULL,
    ENOANO,
    EBADRQC,
    EBADSLT,
    EBFONT,
    ENOSTR,
    ENODATA,
    ETIME,
    ENOSR,
    ENONET,
    ENOPKG,
    EREMOTE,
    ENOLINK,
    EADV,
    ESRMNT,
    ECOMM,
    EPROTO,
    EMULTIHOP,
    EDOTDOT,
    EBADMSG,
    ENOTUNIQ,
    EBADFD,
    EREMCHG,
    ELIBACC,
    ELIBBAD,
    ELIBSCN,
    ELIBMAX,
    ELIBEXEC,
    ENOSYS,
    ENOTEMPTY,
    ENAMETOOLONG,
    ELOOP,
    EOPNOTSUPP,
    EPFNOSUPPORT,
    ECONNRESET,
    ENOBUFS,
    EAFNOSUPPORT,
    EPROTOTYPE,
    ENOTSOCK,
    ENOPROTOOPT,
    ESHUTDOWN,
    ECONNREFUSED,
    EADDRINUSE,
    ECONNABORTED,
    ENETUNREACH,
    ENETDOWN,
    ETIMEDOUT,
    EHOSTDOWN,
    EHOSTUNREACH,
    EINPROGRESS,
    EALREADY,
    EDESTADDRREQ,
    EMSGSIZE,
    EPROTONOSUPPORT,
    ESOCKTNOSUPPORT,
    EADDRNOTAVAIL,
    ENETRESET,
    EISCONN,
    ENOTCONN,
    ETOOMANYREFS,
    EUSERS,
    EDQUOT,
    ESTALE,
    ENOMEDIUM,
    EILSEQ,
    EOVERFLOW,
    ECANCELED,
    ENOTRECOVERABLE,
    EOWNERDEAD,
    ESTRPIPE,
    EUNKNOWN,
};

pub fn fromErrno(errno_val: c_int) ErrnoError {
    return switch (errno_val) {
        1 => error.EPERM,
        2 => error.ENOENT,
        3 => error.ESRCH,
        4 => error.EINTR,
        5 => error.EIO,
        6 => error.ENXIO,
        7 => error.E2BIG,
        8 => error.ENOEXEC,
        9 => error.EBADF,
        10 => error.ECHILD,
        11 => error.EAGAIN,
        12 => error.ENOMEM,
        13 => error.EACCES,
        14 => error.EFAULT,
        15 => error.ENOTBLK,
        16 => error.EBUSY,
        17 => error.EEXIST,
        18 => error.EXDEV,
        19 => error.ENODEV,
        20 => error.ENOTDIR,
        21 => error.EISDIR,
        22 => error.EINVAL,
        23 => error.ENFILE,
        24 => error.EMFILE,
        25 => error.ENOTTY,
        26 => error.ETXTBSY,
        27 => error.EFBIG,
        28 => error.ENOSPC,
        29 => error.ESPIPE,
        30 => error.EROFS,
        31 => error.EMLINK,
        32 => error.EPIPE,
        33 => error.EDOM,
        34 => error.ERANGE,
        35 => error.ENOMSG,
        36 => error.EIDRM,
        37 => error.ECHRNG,
        38 => error.EL2NSYNC,
        39 => error.EL3HLT,
        40 => error.EL3RST,
        41 => error.ELNRNG,
        42 => error.EUNATCH,
        43 => error.ENOCSI,
        44 => error.EL2HLT,
        45 => error.EDEADLK,
        46 => error.ENOLCK,
        50 => error.EBADE,
        51 => error.EBADR,
        52 => error.EXFULL,
        53 => error.ENOANO,
        54 => error.EBADRQC,
        55 => error.EBADSLT,
        57 => error.EBFONT,
        60 => error.ENOSTR,
        61 => error.ENODATA,
        62 => error.ETIME,
        63 => error.ENOSR,
        64 => error.ENONET,
        65 => error.ENOPKG,
        66 => error.EREMOTE,
        67 => error.ENOLINK,
        68 => error.EADV,
        69 => error.ESRMNT,
        70 => error.ECOMM,
        71 => error.EPROTO,
        74 => error.EMULTIHOP,
        76 => error.EDOTDOT,
        77 => error.EBADMSG,
        80 => error.ENOTUNIQ,
        81 => error.EBADFD,
        82 => error.EREMCHG,
        83 => error.ELIBACC,
        84 => error.ELIBBAD,
        85 => error.ELIBSCN,
        86 => error.ELIBMAX,
        87 => error.ELIBEXEC,
        88 => error.ENOSYS,
        90 => error.ENOTEMPTY,
        91 => error.ENAMETOOLONG,
        92 => error.ELOOP,
        95 => error.EOPNOTSUPP,
        96 => error.EPFNOSUPPORT,
        104 => error.ECONNRESET,
        105 => error.ENOBUFS,
        106 => error.EAFNOSUPPORT,
        107 => error.EPROTOTYPE,
        108 => error.ENOTSOCK,
        109 => error.ENOPROTOOPT,
        110 => error.ESHUTDOWN,
        111 => error.ECONNREFUSED,
        112 => error.EADDRINUSE,
        113 => error.ECONNABORTED,
        114 => error.ENETUNREACH,
        115 => error.ENETDOWN,
        116 => error.ETIMEDOUT,
        117 => error.EHOSTDOWN,
        118 => error.EHOSTUNREACH,
        119 => error.EINPROGRESS,
        120 => error.EALREADY,
        121 => error.EDESTADDRREQ,
        122 => error.EMSGSIZE,
        123 => error.EPROTONOSUPPORT,
        124 => error.ESOCKTNOSUPPORT,
        125 => error.EADDRNOTAVAIL,
        126 => error.ENETRESET,
        127 => error.EISCONN,
        128 => error.ENOTCONN,
        129 => error.ETOOMANYREFS,
        131 => error.EUSERS,
        132 => error.EDQUOT,
        133 => error.ESTALE,
        135 => error.ENOMEDIUM,
        138 => error.EILSEQ,
        139 => error.EOVERFLOW,
        140 => error.ECANCELED,
        141 => error.ENOTRECOVERABLE,
        142 => error.EOWNERDEAD,
        143 => error.ESTRPIPE,
        else => error.EUNKNOWN,
    };
}

pub fn checkErrno(comptime T: type, ret: T) ErrnoError!T {
    const info = @typeInfo(T);
    const sentinel: T = switch (info) {
        .int => |i| switch (i.signedness) {
            .signed => -1,
            .unsigned => ~@as(T, 0),
        },
        .comptime_int => -1,
        else => @compileError("checkErrno requires an integer type"),
    };
    if (ret == sentinel) {
        @branchHint(.unlikely);
        return fromErrno(inet.sceNetInetGetErrno());
    }
    return ret;
}
