// THIS FILE IS AUTO-GENERATED
pub const types = @import("types.zig");

pub usingnamespace types; // DEPRECATED

// DEPRECATED, use namespaces instead
pub usingnamespace @import("module/sceCtrl.zig");
pub usingnamespace @import("module/sceAudio.zig");
pub usingnamespace @import("module/sceAudiocodec.zig");
pub usingnamespace @import("module/scePower.zig");
pub usingnamespace @import("module/sceVaudio.zig");
pub usingnamespace @import("module/sceNetInet.zig");
pub usingnamespace @import("module/sceNetApctl.zig");
pub usingnamespace @import("module/sceNetAdhocctl.zig");
pub usingnamespace @import("module/sceSsl.zig");
pub usingnamespace @import("module/sceNetAdhoc.zig");
pub usingnamespace @import("module/sceNetAdhocMatching.zig");
pub usingnamespace @import("module/sceNet.zig");
pub usingnamespace @import("module/sceNetResolver.zig");
pub usingnamespace @import("module/sceNet_lib.zig");
pub usingnamespace @import("module/sceHttp.zig");
pub usingnamespace @import("module/sceOpenPSID.zig");
pub usingnamespace @import("module/sceAtrac3plus.zig");
pub usingnamespace @import("module/sceSuspendForUser.zig");
pub usingnamespace @import("module/IoFileMgrForUser.zig");
pub usingnamespace @import("module/sceImpose.zig");
pub usingnamespace @import("module/UtilsForUser.zig");
pub const threadman = @import("module/ThreadManForUser.zig");
pub const loadexec = @import("module/LoadExecForUser.zig");
pub usingnamespace @import("module/InterruptManager.zig");
pub usingnamespace @import("module/SysMemUserForUser.zig");
pub usingnamespace @import("module/ModuleMgrForUser.zig");
pub usingnamespace @import("module/StdioForUser.zig");
pub usingnamespace @import("module/Kernel_Library.zig");
pub usingnamespace @import("module/sceWlanDrv.zig");
pub usingnamespace @import("module/sceWlanDrv_lib.zig");
pub usingnamespace @import("module/sceHprm.zig");
pub usingnamespace @import("module/sceMp3.zig");
pub usingnamespace @import("module/sceUtility.zig");
pub usingnamespace @import("module/sceUtility_netparam_internal.zig");
pub usingnamespace @import("module/sceKermitPeripheral.zig");
pub const ge = @import("module/sceGe_user.zig");
pub usingnamespace @import("module/sceJpeg.zig");
pub usingnamespace @import("module/sceMpegbase.zig");
pub usingnamespace @import("module/sceMpeg.zig");
pub usingnamespace @import("module/sceUsbstor.zig");
pub usingnamespace @import("module/sceRtc.zig");
pub usingnamespace @import("module/sceUmdUser.zig");
pub usingnamespace @import("module/sceReg.zig");
pub usingnamespace @import("module/sceUsb.zig");
pub usingnamespace @import("module/sceUsbCam.zig");
pub usingnamespace @import("module/sceDmac.zig");
pub usingnamespace @import("module/sceDisplay.zig");

// DEPRECATED, use types directly instead
const ScePspSRect = types.ScePspSRect;
const ScePspIRect = types.ScePspIRect;
const ScePspL64Rect = types.ScePspL64Rect;
const ScePspFRect = types.ScePspFRect;
const ScePspSVector2 = types.ScePspSVector2;
const ScePspIVector2 = types.ScePspIVector2;
const ScePspL64Vector2 = types.ScePspL64Vector2;
const ScePspFVector2 = types.ScePspFVector2;
const ScePspVector2 = types.ScePspVector2;
const ScePspSVector3 = types.ScePspSVector3;
const ScePspIVector3 = types.ScePspIVector3;
const ScePspL64Vector3 = types.ScePspL64Vector3;
const ScePspFVector3 = types.ScePspFVector3;
const ScePspVector3 = types.ScePspVector3;
const ScePspSVector4 = types.ScePspSVector4;
const ScePspIVector4 = types.ScePspIVector4;
const ScePspL64Vector4 = types.ScePspL64Vector4;
const ScePspFVector4 = types.ScePspFVector4;
const ScePspFVector4Unaligned = types.ScePspFVector4Unaligned;
const ScePspVector4 = types.ScePspVector4;
const ScePspIMatrix2 = types.ScePspIMatrix2;
const ScePspFMatrix2 = types.ScePspFMatrix2;
const ScePspMatrix2 = types.ScePspMatrix2;
const ScePspIMatrix3 = types.ScePspIMatrix3;
const ScePspFMatrix3 = types.ScePspFMatrix3;
const ScePspMatrix3 = types.ScePspMatrix3;
const ScePspIMatrix4 = types.ScePspIMatrix4;
const ScePspIMatrix4Unaligned = types.ScePspIMatrix4Unaligned;
const ScePspFMatrix4 = types.ScePspFMatrix4;
const ScePspFMatrix4Unaligned = types.ScePspFMatrix4Unaligned;
const ScePspMatrix4 = types.ScePspMatrix4;
const ScePspFQuaternion = types.ScePspFQuaternion;
const ScePspFQuaternionUnaligned = types.ScePspFQuaternionUnaligned;
const ScePspFColor = types.ScePspFColor;
const ScePspFColorUnaligned = types.ScePspFColorUnaligned;
const ScePspRGBA8888 = types.ScePspRGBA8888;
const ScePspRGBA4444 = types.ScePspRGBA4444;
const ScePspRGBA5551 = types.ScePspRGBA5551;
const ScePspRGB565 = types.ScePspRGB565;
const ScePspUnion32 = types.ScePspUnion32;
const ScePspUnion64 = types.ScePspUnion64;
const ScePspUnion128 = types.ScePspUnion128;
const ScePspDateTime = types.ScePspDateTime;
