pub const SceSysTimerId = c_int;
pub extern fn sceSTimerAlloc() SceSysTimerId;
pub extern fn sceSTimerFree(timer: SceSysTimerId) void;
pub extern fn sceSTimerStartCount(timer: SceSysTimerId) void;
pub extern fn sceSTimerStopCount(timer: SceSysTimerId) void;
pub extern fn sceSTimerResetCount(timer: SceSysTimerId) void;
pub extern fn sceSTimerGetCount(timer: SceSysTimerId, count: [*c]c_int) void;
pub extern fn sceSTimerSetHandler(timer: SceSysTimerId, cycle: c_int, handler: ?fn () callconv(.C) c_int, unk1: c_int) void;
pub extern fn SysTimerForKernel_53231A15(timer: SceSysTimerId, unk1: c_int) void;
pub extern fn SysTimerForKernel_B53534B4(timer: SceSysTimerId, unk1: c_int, unk2: c_int) void;
